spring.application.name=MTS second semester
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
